FROM python:3.12

# 시스템 패키지 설치
RUN apt-get update && apt-get install -y \
  libreoffice \
  poppler-utils \
  && apt-get clean

# 필요 패키지 설치
COPY requirements.txt .
RUN pip install -r requirements.txt

# 애플리케이션 복사
COPY . /app
WORKDIR /app

CMD alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000