FROM python:3.12

# 시스템 패키지 설치
RUN apt-get update && apt-get install -y \
  libreoffice \
  poppler-utils \
  fonts-nanum \
  locales \
  && apt-get clean

# UTF-8 로케일 설정
RUN sed -i '/ko_KR.UTF-8/s/^# //g' /etc/locale.gen && \
  locale-gen ko_KR.UTF-8

ENV LANG=ko_KR.UTF-8
ENV LANGUAGE=ko_KR:ko
ENV LC_ALL=ko_KR.UTF-8

# 워킹 디렉토리 설정
WORKDIR /app

# 의존성 먼저 복사 → 캐시 최적화
COPY requirements.txt ./
RUN pip install -r requirements.txt

# 애플리케이션 복사
COPY . /app

CMD alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000